#!/bin/bash

set -e


list_layers() {
	git config --name-only --get-regexp 'layer\.[^.]*\.url' |
	sed -e 's/^layer\.//' -e 's/\.url$//' |
	{
		while read layer; do
			if [ $(git config --get layer.$layer.skip) ]; then
				echo >&2 "[$layer] Skipping"
				continue
			fi
			echo "$layer"
		done
	}
}

update_all_sources() {
	echo "--- Checking layer remote sources for updates"
	list_layers | {
		while read layer; do
			update_source $layer
		done
	}
}

update_source() {
	layer=$1
	url=$(git config --get layer.$layer.url)
	branch=$(git config --get layer.$layer.branch)
	echo "[$layer] fetching $url $branch"
	git fetch $url $branch:layers/$layer/src
}


update_all_caches() {
	echo "--- Updating layer caches"
	list_layers | {
		while read layer; do
			update_cache $layer
		done
	}
}

get_mountpoint() {
	echo "pkg/$1"
}

update_cache() {
	layer=$1
	src=layers/$layer/src
	tmp=layers/$layer/tmp/$RANDOM
	cache=layers/$layer/cache
	git branch $tmp $src
	mountpoint=$(get_mountpoint "$layer")
	transform_branch $tmp $mountpoint
	echo "[$layer] moving $tmp to $cache"
	git branch -m -f $tmp $cache
}

transform_branch() {
	branch=$1
	mountpoint=$2

	if [ -z "$mountpoint" ]; then
		return
	fi
	git filter-branch -f --index-filter "
		git ls-files -s |
		{
			while read line; do
				echo \"\${line/	/	$mountpoint/}\"
			done
		}
	" $branch
}



# Change the working directory to the root of the git repo
REPOROOT=$(git rev-parse --show-toplevel)

export GIT_DIR=$REPOROOT/.git
TMP=$(mktemp -d)
export GIT_WORK_TREE=$TMP
cd $GIT_WORK_TREE

# Initialize an empty temporary index file
TMP2=$(mktemp)
cp $GIT_DIR/index $TMP2
export GIT_INDEX_FILE=$TMP2
echo '100644 8a1218a1024a212bb3db30becd860315f9f3ac52 0	foo' | git update-index --index-info
git rm --cached foo

update_all_sources
update_all_caches

rm -fr "$TMP"
rm -f "$TMP2"
